[tools]
node = "22"
gh = "2"

# =================================================================================================
# CI Tools
# =================================================================================================
"aqua:rhysd/actionlint" = "1"
"npm:@commitlint/cli" = "20"
