[tools]
node = "24"
gh = "2.98.0"

# =================================================================================================
# CI Tools
# =================================================================================================
"aqua:rhysd/actionlint" = "1"
"npm:@commitlint/cli" = "21"
