---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Check Transpiled JavaScript
permissions:
  contents: write

on:
  push: {}

jobs:
  check-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with: { token: '${{ secrets.GITHUB_TOKEN }}' }

      - name: Setup mise
        uses: jdx/mise-action@eb2f5cb41b0a8175dad2f797e3daca6fe7795a19 # v2.4.2

      - name: Build dist/ Directory
        run: npm ci && npm run build

      - name: Check for changes
        id: check-changes
        run: |
          if [ ! -d dist/ ]; then
            echo "Expected dist/ directory does not exist. See status below:"
            ls -la ./
            exit 1
          fi

          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
            echo "Detected uncommitted changes in dist/"
            git diff --ignore-space-at-eol --text dist/
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
            echo "No changes detected in dist/"
          fi

      - name: Commit and push changes
        if: steps.check-changes.outputs.has_changes == 'true' && github.ref == 'refs/heads/main'
        env:
          CI_COMMIT_AUTHOR: mr-borboto[bot]
          CI_COMMIT_MESSAGE: 'chore: update dist [skip ci]'
          CI_COMMIT_EMAIL: 170036086+mr-borboto[bot]@users.noreply.github.com
        run: |
          echo "On main branch - committing and pushing changes"
          git config --local user.email "${{ env.CI_COMMIT_EMAIL }}"
          git config --local user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git add dist/
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push

      - name: Fail if changes on non-main branch
        if: steps.check-changes.outputs.has_changes == 'true' && github.ref != 'refs/heads/main'
        run: |
          echo "Error: Uncommitted changes detected in dist/ on non-main branch"
          echo "Branch: ${{ github.ref }}"
          echo "Please build and commit the dist/ directory before pushing"
          exit 1
