---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: ESLint
permissions: { contents: read }

on:
  workflow_dispatch: {}
  push:
    paths:
      - '**.js'
      - '.eslint.config.mjs'
      - '.eslintignore'
      - 'package*.json'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup mise
        uses: jdx/mise-action@ca0c5fc9c8a8386dae8ba5d37608a083a307991c # v3.1.0

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint:check
